services:

  # ========================
  # Kafka (KRaft mode)
  # ========================
  broker:
    healthcheck:
      test: [ "CMD", "bash", "-c", "nc -z localhost 9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker:29093
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://broker:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk



  # ========================
  # Postgres DBs
  # ========================
  mysql-order:
    container_name: mysql-order
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
      MYSQL_USER: ptechie
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-order:/var/lib/mysql
    restart: unless-stopped

  mysql-inventory:
    container_name: mysql-inventory
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: ptechie
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-inventory:/var/lib/mysql
    restart: unless-stopped

  # ========================
  # Mongo
  # ========================
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  # ========================
  # Keycloak + MySQL (FIXED)
  # ========================
  keycloak-mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
        - ./mysql-keycloak:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-mysql

  # ========================
  # Zipkin
  # ========================
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  # ========================
  # Eureka
  # ========================
  discovery-server:
    image: dvdr/discovery-server:latest
    pull_policy: never
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  # ========================
  # API Gateway
  # ========================
  api-gateway:
    image: dvdr/api-gateway:latest
    container_name: api-gateway
    pull_policy: never
    ports:
      - "8181:8080"
    expose:
      - 8181
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server
      - keycloak
      - zipkin

  # ========================
  # Services
  # ========================
  product-service:
    container_name: product-service
    pull_policy: never
    image: dvdr/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo
      - discovery-server
      - api-gateway

  order-service:
    container_name: order-service
    image: dvdr/order-service:latest
    pull_policy: never
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/order-service
      - SPRING_DATASOURCE_USERNAME=ptechie
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql-order
      - broker
      - zipkin
      - discovery-server
      - api-gateway

  inventory-service:
    container_name: inventory-service
    image: dvdr/inventory-service:latest
    pull_policy: never
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-inventory:3306/inventory-service
      - SPRING_DATASOURCE_USERNAME=ptechie
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql-inventory
      - discovery-server
      - api-gateway

  notification-service:
    container_name: notification-service
    image: dvdr/notification-service:latest
    pull_policy: never
    restart: always
    #build: ./notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
    depends_on:
      zipkin:
        condition: service_started
      broker:
        condition: service_healthy
      discovery-server:
        condition: service_started
      api-gateway:
        condition: service_started

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    depends_on:
      - product-service
      - inventory-service
      - order-service
      - notification-service



  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
